---
- hosts: localhost
  tasks:
    - name: copy the cloudwatch config file
      copy:
        src: cloudwatch-config.json
        dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
      become: yes
    - name: start cloudwatch agent
      shell:
        "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json"
      register: cloudwatchcmd
    - debug: msg="{{cloudwatchcmd.stdout}}"